server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
          __docker_container_name__: "{{ .ContainerName }}"
          __container_id__: "{{ .ContainerID }}"  # Adding container ID label
          __app_name__: "httpd"                   # Custom app label, adjust as needed
