server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
          __docker_container_name__: "{{ .ContainerName }}"  # Existing container name label
          __service__: "{{ .ContainerName }}"  # Adding a service label based on the container name
          __name__: "{{ .ContainerName }}"  # Override the default __name__ label with container name
